# Proiect 2 — Procesarea datelor

---

## Pasul 1 — Importarea bibliotecilor

Importăm `pandas` pentru manipularea datelor și `numpy` pentru operații numerice. În etapele următoare vom importa, la nevoie, clase din `scikit-learn` pentru codificare și scalare.

In [1]:
import pandas as pd
import numpy as np

---

## Pasul 2 — Încărcarea și analiza setului de date

### 2.1. Importarea setului de date

Funcția `pd.read_csv()` încarcă fișierul CSV într-un obiect `DataFrame`, o structură tabelară care permite selectarea coloanelor, calcularea statisticilor și tratarea valorilor lipsă.

In [2]:
dataset = pd.read_csv("Dataset.csv")

### 2.2. Analizarea dimensiunii

Atributul `shape` returnează un tuplu cu numărul de rânduri și numărul de coloane. Pentru setul inițial din notebook, dimensiunea este `(11, 4)`.

In [3]:
dataset.shape

(11, 4)

### 2.3. Inspectarea primelor observații

Metoda `head()` afișează primele cinci rânduri implicit. Pentru a afișa primele zece rânduri, se poate folosi `dataset.head(10)`.

In [4]:
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0       No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No
3    Spain  38.0  61000.0       No
4  Germany  40.0      NaN       Yes

### 2.4. Verificarea tipurilor de date

`dataset.dtypes` arată tipul de date al fiecărei coloane. În acest set, `Country` și `Purchased` sunt coloane categoriale stocate ca șiruri de caractere, iar `Age` și `Salary` sunt numerice.

In [5]:
data_types = dataset.dtypes
print(data_types)

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

### 2.5. Identificarea valorilor lipsă

Valorile lipsă sunt adesea reprezentate de `NaN`. Expresia `dataset.isnull()` produce un tabel de valori booleene, iar `sum()` numără valorile lipsă din fiecare coloană.

In [6]:
isnull = dataset.isnull().sum()
print(isnull)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

În setul de date folosit de notebook, `Age` și `Salary` au câte o valoare lipsă. Celelalte coloane nu au valori lipsă.

### 2.6. Statistici descriptive

`describe(include="all")` afișează un rezumat atât pentru coloanele numerice, cât și pentru cele categoriale. Pentru coloanele numerice include, printre altele, media, abaterea standard, minimul, quartilele și maximul. Pentru coloanele categoriale afișează numărul de valori, valorile unice, categoria cea mai frecventă și frecvența ei. Statisticile care nu se aplică unui tip de coloană sunt afișate ca `NaN`.

In [7]:
dataset.describe(include="all")

       Country        Age        Salary Purchased
count       11  10.000000     10.000000        11
unique       3        NaN           NaN         2
top     France        NaN           NaN       No
freq         4        NaN           NaN         6
mean       NaN  38.700000  63500.000000       NaN
std        NaN   7.257946  11597.413505       NaN
min        NaN  27.000000  48000.000000       NaN
25%        NaN  35.500000  55000.000000       NaN
50%        NaN  38.000000  61000.000000       NaN
75%        NaN  43.000000  70750.000000       NaN
max        NaN  50.000000  83000.000000       NaN

### 2.7. Eliminarea rândurilor duplicate

Duplicatele pot influența statisticile și pot face ca anumite observații să fie reprezentate de mai multe ori decât ar trebui. `drop_duplicates()` returnează un tabel din care au fost eliminate rândurile identice. În notebook, rezultatul este atribuit din nou variabilei `dataset`.

In [8]:
dataset = dataset.drop_duplicates()
dataset.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

După eliminarea duplicatelor, setul de date conține 10 rânduri. Verifică întotdeauna dacă două înregistrări identice sunt într-adevăr duplicate nedorite; în anumite contexte, observații care arată la fel pot fi evenimente distincte.

### 2.8. Separarea caracteristicilor și a variabilei țintă

În acest exemplu:

- `X` conține caracteristicile de intrare (`Country`, `Age` și `Salary`);
- `Y` conține variabila țintă/dependentă (`Purchased`), pe care am putea dori să o prezicem într-o etapă ulterioară.

Este util să separăm caracteristicile de țintă înainte de a aplica transformări diferite asupra lor.

In [9]:
X = dataset[['Country', 'Age', 'Salary']]
Y = dataset['Purchased']

### 2.9. Inspectarea caracteristicilor și a țintei

In [10]:
print(X)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [11]:
print(Y)

0    No
1    Yes
2    No
3    No
4    Yes
5    Yes
6    No
7    Yes
8    No
9    Yes
Name: Purchased, dtype: object

În acest punct, `X` este un `DataFrame` cu trei coloane, iar `Y` este o serie pandas cu etichetele `No` și `Yes`. În fișier pot exista spații suplimentare în unele valori textuale; curățarea spațiilor este o operație uzuală înainte de codificarea categoriilor.

---

## Pasul 3 — Tratarea valorilor lipsă

In [12]:
mean_age = X['Age'].mean()
X.fillna({'Age': mean_age}, inplace=True)
print(X)

   Country        Age   Salary
0   France  44.000000  72000.0
1    Spain  27.000000  48000.0
2  Germany  30.000000  54000.0
3    Spain  38.000000  61000.0
4  Germany  40.000000      NaN
5   France  35.000000  58000.0
6    Spain  38.777778  52000.0
7   France  48.000000  79000.0
8  Germany  50.000000  83000.0
9   France  37.000000  67000.0

/tmp/ipykernel_1957/3009324645.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna({'Age': mean_age}, inplace=True)

Media vârstei calculată din observațiile disponibile este aproximativ `38.7778`. Valoarea lipsă este înlocuită cu această medie.

### 3.2. Imputarea mediei pentru `Salary`

Aplicăm același procedeu coloanei `Salary`.

In [13]:
mean_salary = X['Salary'].mean()
X.fillna({'Salary': mean_salary}, inplace=True)
print(X)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

/tmp/ipykernel_1957/2129726686.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna({'Salary': mean_salary}, inplace=True)

Media salariului calculată din valorile disponibile este aproximativ `63777.7778`. După această operație, `X` nu mai conține valori lipsă în coloanele numerice.

> **Limitare importantă:** imputarea cu media este folosită aici pentru a ilustra tehnica. Într-un proiect real, trebuie verificat de ce lipsesc datele și dacă media este o alegere rezonabilă. În evaluarea unui model, valorile de imputare trebuie calculate doar pe datele de antrenare și apoi aplicate datelor de validare/test, pentru a evita scurgerea de informație (*data leakage*).

---

## Pasul 4 — Transformarea variabilelor categoriale

Multe metode de învățare automată operează cu intrări numerice. În acest exemplu, `Country` și `Purchased` sunt variabile categoriale, deci trebuie reprezentate numeric înainte de a le folosi cu astfel de algoritmi.

### 4.1. Codificarea One-Hot pentru `Country`

O codificare simplă, de tipul France = 0, Spain = 1 și Germany = 2, ar introduce o ordine numerică artificială între țări. Pentru această caracteristică nominală, nu există o asemenea ordine. **One-Hot Encoding** creează câte o coloană indicator pentru fiecare categorie, cu valori `True`/`False` (sau `1`/`0`, în funcție de reprezentare).

In [14]:
X = pd.get_dummies(X, columns=['Country'])  # One-Hot Encoding
print(X)

         Age        Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.000000            True            False          False
1  27.000000  48000.000000           False            False           True
2  30.000000  54000.000000           False             True          False
3  38.000000  61000.000000           False            False           True
4  40.000000  63777.777778           False             True          False
5  35.000000  58000.000000            True            False          False
6  38.777778  52000.000000           False            False           True
7  48.000000  79000.000000            True            False          False
8  50.000000  83000.000000           False             True          False
9  37.000000  67000.000000            True            False          False

Rezultatul conține coloane precum `Country_France`, `Country_Germany` și `Country_Spain`. Pentru fiecare observație, coloana corespunzătoare țării sale este activă, iar celelalte sunt inactive. În această reprezentare, categoriile nu mai sunt codificate ca numere ordonate.

Ordinea coloanelor generate de `pd.get_dummies()` este stabilită de pandas, de regulă în ordine alfabetică. De aceea, este mai sigur să interpretezi numele coloanelor decât să presupui că o categorie corespunde unei anumite poziții fără să verifici rezultatul.

### 4.2. Codificarea variabilei țintă `Purchased`

Pentru acest exemplu binar, folosim `LabelEncoder` pentru a transforma etichetele textuale ale variabilei țintă în etichete numerice.

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()  # Transformă etichetele în valori numerice
Y = le.fit_transform(Y.astype(str).str.strip())
print(Y)

[0 1 0 0 1 1 0 1 0 1]

`LabelEncoder` atribuie codurile pe baza ordinii sortate a claselor. În acest set, `No` este codificat ca `0`, iar `Yes` ca `1`. Folosirea `.str.strip()` elimină spațiile suplimentare de la începutul sau sfârșitul valorilor textuale înainte de codificare.

Pentru a verifica asocierea exactă dintre coduri și etichete, rulează:

In [16]:
print("Clasele și ordinea lor:", le.classes_)

Clasele și ordinea lor: ['No' 'Yes']

> **Notă:** `LabelEncoder` este potrivit aici pentru codificarea variabilei țintă `Y`. Pentru caracteristici nominale precum `Country`, One-Hot Encoding evită interpretarea greșită a etichetelor ca o scară numerică ordonată.

---

## Pasul 5 — Scalarea caracteristicilor

`MinMaxScaler` transformă o caracteristică astfel încât minimul observat să devină `0`, iar maximul observat să devină `1`. Valorile intermediare sunt mapate în același interval.

### 5.1. Scalarea caracteristicilor din `X` — varianta din notebook

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # Scalează valorile într-un interval între 0 și 1
X_all_scaled = scaler.fit_transform(X)

print(X_all_scaled)

[[0.73913043 0.68571429 1.         0.         0.        ]
 [0.         0.         0.         0.         1.        ]
 [0.13043478 0.17142857 0.         1.         0.        ]
 [0.47826087 0.37142857 0.         0.         1.        ]
 [0.56521739 0.45079365 0.         1.         0.        ]
 [0.34782609 0.28571429 1.         0.         0.        ]
 [0.51207729 0.11428571 0.         0.         1.        ]
 [0.91304348 0.88571429 1.         0.         0.        ]
 [1.         1.         0.         1.         0.        ]
 [0.43478261 0.54285714 1.         0.         0.        ]]

După această operație, `X` devine un tablou NumPy, nu un `DataFrame`; numele coloanelor nu mai sunt atașate automat rezultatului. Pentru acest set de date, coloanele One-Hot sunt deja binare (`0`/`1` sau `False`/`True`), astfel că valorile lor rămân la capetele intervalului.

In [18]:
X_scaled = X.copy()
scaler = MinMaxScaler()

X_scaled[['Age', 'Salary']] = scaler.fit_transform(
    X_scaled[['Age', 'Salary']]
)

print(X_scaled)

        Age    Salary  Country_France  Country_Germany  Country_Spain
0  0.739130  0.685714            True            False          False
1  0.000000  0.000000           False            False           True
2  0.130435  0.171429           False             True          False
3  0.478261  0.371429           False            False           True
4  0.565217  0.450794           False             True          False
5  0.347826  0.285714            True            False          False
6  0.512077  0.114286           False            False           True
7  0.913043  0.885714            True            False          False
8  1.000000  1.000000           False             True          False
9  0.434783  0.542857            True            False          False